services:
  user-service:
    build:
      context: ./user-service
    environment:
      PORT: ${PORT}
      MONGODB_URI: ${DATABASE_URL}
    ports:
      - "${PORT}:${PORT}"
  
  task-service:
    build:
      context: ./task-service
    environment:
      PORT: ${PORT2}
      MONGODB_URI: ${DATABASE_URL}
    ports:
      - "${PORT2}:${PORT2}"
