GET http://localhost:3002/health

###

POST http://localhost:3002/task
Content-Type: application/json

{
    "title": "Complete task 5 Sidd",
    "description": "The deadline is to complete task 5 Sidd by end of tomorrow",
    "userId": "6a14803add9bf8dd5f9df4cb"
}

###

GET http://localhost:3002/tasks

